In [1]:
import pandas as pd
import numpy as np
from scipy import stats

df = pd.read_excel(
    "Данные для тестового задания.xlsx",
    sheet_name="Данные АБ тестов"
)

df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [2]:
df['experiment_num'].value_counts().sort_index()

experiment_num
1    945
2    945
3    945
Name: count, dtype: int64

In [3]:
arpu = (
    df.groupby(['experiment_num', 'experiment_group'])
      .agg(
          users=('user_id', 'nunique'),
          revenue=('revenue', 'sum')
      )
)

arpu['ARPU'] = arpu['revenue'] / arpu['users']

arpu

                                 users  revenue        ARPU
experiment_num experiment_group
1              control             465   335944  722.460215
               test                480   319555  665.739583
2              control             465   327664  704.653763
               test                480   159806  332.929167
3              control             465   308391  663.206452
               test                480   479361  998.668750

In [4]:
for exp in sorted(df['experiment_num'].unique()):

    exp_df = df[df['experiment_num'] == exp]

    control = exp_df[
        exp_df['experiment_group'] == 'control'
    ]['revenue']

    test = exp_df[
        exp_df['experiment_group'] == 'test'
    ]['revenue']

    stat, pvalue = stats.ttest_ind(
        control,
        test,
        equal_var=False
    )

    print(f'Experiment {exp}')
    print(f'p-value = {pvalue:.6f}')
    print('-' * 30)

Experiment 1
p-value = 0.688966
------------------------------
Experiment 2
p-value = 0.001128
------------------------------
Experiment 3
p-value = 0.060315
------------------------------

In [8]:
import pandas as pd

listers = pd.read_excel(
    'Данные для тестового задания.xlsx',
    sheet_name='Листеры'
)

listers.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [9]:
ARPU = listers['revenue'].sum() / listers['user_id'].nunique()

print(ARPU)

2043.0910052910053